services:
  app:
    build: .
    ports:
      - "4019:4019"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=4019
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4019/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Development service (for docker compose -f docker-compose.dev.yml up)
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "4019:4019"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4019
    command: npm run dev
    profiles:
      - dev